flexr/flexr/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('flexr_web.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

]

flexr/flexr_web/urls.py
from django.urls import path

from . import views
from .class_views.AccountPreferencesView import AccountPreferencesAPIView
from .class_views.SuggestedSitesView import SuggestedSiteAPIView
from .views import *

# Gerald: probably a better way to do this, but I'm dumb
from .class_views.AccountView import AccountViewWeb
from .class_views.AccountView import AccountViewAPI
from .class_views.BookmarksView import BookmarksView, BookmarksViewAPI
from .class_views.HistoryView import HistoryView, HistoryViewAPI
from .class_views.IndexView import IndexView
from .class_views.NoteView import NoteView
from .class_views.NotesView import NotesView
from .class_views.ProfileView import ProfileView
from .class_views.SharedFolderView import SharedFolderView
from .class_views.BookmarkFolderView import BookmarkFolderView, BookmarkFoldersViewAPI
from .class_views.SharedFoldersView import SharedFoldersView
from .class_views.TabsView import TabsView, TabAPIView
from .class_views.UserView import UserAPIView
from .class_views.FriendView import FriendViewWeb, FriendAPIView
from .class_views.SiteView import SiteAPIView
from .class_views.NoteView import NoteViewAPI
from .class_views.SharedFolderView import FoldersViewAPI

urlpatterns = [
    path('register', views.register_web, name='register'),

    path('', IndexView.as_view(), name='index'), #broken

    path('add_account/', AccountViewWeb().add_account, name = "add account"),
    path('switch_account/<id>/', AccountViewWeb().switch_account, name = "switch account"),
    path('delete_account/<int:pk>/', AccountViewWeb().delete, name="delete account"),

    path('browsing_history/', HistoryView.as_view(), name='history'),
    path('browsing_history/delete/', HistoryView().delete, name='delete history'),

    path('notes/', NotesView.as_view(), name='notes'), #broken
    path('search_notes/', NotesView().search_note, name='search_notes'), #broken
    path('create_note/', NotesView().create_note, name='create_note'),
    path('note/<int:pk>/', NoteView.as_view(), name='note-detail'),
    path('delete-note/<int:pk>/', NotesView().delete_note, name='delete_note'),

    path('opennote/<int:pk>/', NoteView.as_view(), name='note-detail'), #broken
    path('edit_note/<int:pk>/', NoteView().edit_note, name='edit_note'),
    path('unlock_note/<int:pk>/', NoteView().unlock_note, name='unlock note'),

    path('open_tabs/', TabsView.as_view(), name='tabs'), #broken
    path('add_tab/', TabsView().add_tab, name = "add tab"),
    path('close_tab/<id>/', TabsView().close_tab, name = "close tab"),

    path('bookmarks/', BookmarksView.as_view(), name = "bookmarks"), #broken
    path('add_bookmark/<id>/', BookmarksView().add_bookmark, name = "add bookmark"),
    path('delete_bookmark/<id>/', BookmarksView().delete_bookmark, name = "delete bookmark"),
    # path('delete_bookmark/<id>/', BookmarksView().delete_bookmark, name = "delete bookmark"),

    path('create_bookmark_folder/', BookmarkFolderView().create_bookmark_folder_web, name='create_bookmark_folder'),
    path('bookmark_folder/<int:pk>/', BookmarkFolderView.as_view(), name='bookmark-folder-detail'),
    path('delete_bookmark_folder/<int:pk>/', BookmarkFolderView().delete_bookmark_folder_web, name='delete-bookmark-folder'),
    path('edit_bookmark_folder/<int:pk>', BookmarkFolderView().edit_bookmark_folder, name='edit_bookmark_folder'),
                        #bookmark id / bookmark_folder_pk
    path('remove_from_folder/<int:id>/<int:pk>/', BookmarkFolderView().remove_from_folder, name='remove_from_folder'),
    path('bookmark_folder/<id>/add_bookmark/', BookmarkFolderView().add_bookmark, name = "add bookmark bookmark"),


    path('shared_folders/', SharedFoldersView.as_view(), name = "shared folders"),
    path('add_shared_folder/', SharedFoldersView().create_shared_folder, name = "add shared folder"),
    path('delete_shared_folder/<int:pk>/', SharedFoldersView().delete_shared_folder, name = "delete_shared_folder"),
    path('edit_shared_folder/<int:pk>/', SharedFolderView().edit_shared_folder, name = "edit_shared_folder"),

    path('shared_folder/<int:pk>/', SharedFolderView.as_view(), name = "shared folder"),
    path('shared_folder/<id>/add_collaborator/', SharedFolderView().add_collaborator, name = "add collaborator"),
    path('shared_folder/<id>/remove_collaborator/', SharedFolderView().remove_collaborator, name = "remove collaborator"),
    path('shared_folder/<id>/add_note/', SharedFolderView().add_note, name = "add note"),
    path('shared_folder/<id>/remove_note/', SharedFolderView().remove_note, name = "remove note"),
    path('shared_folder/<id>/add_tab/', SharedFolderView().add_tab, name = "add tab"),
    path('shared_folder/<id>/remove_tab/', SharedFolderView().remove_tab, name = "remove tab"),
    path('shared_folder/<id>/add_bookmark/', SharedFolderView().add_bookmark, name = "add bookmark"),
    path('shared_folder/<id>/remove_bookmark/', SharedFolderView().remove_bookmark, name = "remove bookmark"),


    path('profile/', ProfileView.as_view(), name='profile'), #broken
    path('edit_account/', ProfileView().edit_account, name="edit account"),
    path('edit_preferences/', ProfileView().edit_account_preferences, name = "edit account preferences"),

    
    path('friends/', FriendViewWeb.as_view(), name ="friends"),
    path('add_friend/', FriendViewWeb().add_friend, name ="add friend"),
    path('deny_friend/<int:pk>', FriendViewWeb().deny_friend, name ="deny friend"),
    path('accept_friend/<int:pk>', FriendViewWeb().accept_friend, name="accept friend"),
    path('remove_friend/<int:pk>', FriendViewWeb().remove_friend, name="remove friend"),
    path('remove_notif/<int:pk>', FriendViewWeb().remove_notif, name="remove notif"),

    #API Endpoints

    path('api/login/', UserAPIView().login),
    path('api/register/', UserAPIView().sign_up),
    path('api/logout/', UserAPIView().logout),
    path('api/status/', UserAPIView().check_status),

    path('api/site/', SiteAPIView.as_view()),
    path('api/suggested_sites/', SuggestedSiteAPIView.as_view()),

    path('api/tabs/', TabAPIView.as_view()),
    path('api/tab/<id>/', TabAPIView.as_view()),
    path('api/tab/<id>/visit/', TabAPIView().visit_tab),

    path('api/account/<id>/', AccountViewAPI.as_view()),
    path('api/accounts/', AccountViewAPI.as_view()),
    path('api/account/<id>/switch/', AccountViewAPI().switch_account, name = "switch account"),

    path('api/friendships/', FriendAPIView.as_view()),
    path('api/friendships/<id>/', FriendAPIView.as_view()),
    path('api/friendships/<id>/accept/', FriendAPIView().accept),
    path('api/friendships/<id>/deny/', FriendAPIView().deny),

    path('api/history/', HistoryViewAPI.as_view()),
    path('api/history/filter/', HistoryViewAPI.as_view()),
    path('api/history/<id>/', HistoryViewAPI.as_view()),
    #path('api/history/<id>/filter', HistoryViewAPI.as_view()),

    path('api/bookmarks/', BookmarksViewAPI.as_view()),
    path('api/bookmarks/<id>/', BookmarksViewAPI.as_view()),
    path('api/bookmarks/all/', BookmarksViewAPI.as_view()),

    path('api/bookmark_folders/', BookmarkFoldersViewAPI.as_view()),
    path('api/bookmark_folders/<id>/', BookmarkFoldersViewAPI.as_view()),

    path('api/account_preferences/', AccountPreferencesAPIView.as_view()),

    path('api/note/<id>/', NoteViewAPI.as_view()),
    path('api/notes/', NoteViewAPI.as_view()),

    path('api/shared_folders/', FoldersViewAPI.as_view()),
    path('api/shared_folders/<id>/', FoldersViewAPI.as_view()),
]

# old patterns
''' 
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('register', views.register_web, name='register'),
    path('profile/', views.profile_web, name='profile'),
    path('open_tabs/', views.active_tabs_web, name='tabs'),
    path('notes/', views.notes_hub_web, name='notes'),
    path('browsing_history/', views.browsing_history_web, name='history'),
    path('api/tabs/', AllTabsView.as_view()),
    path('api/tab/<id>', TabView.as_view()),
    path('api/tab/', TabView.as_view()),
    path('create_note', create_note, name='create_note'),
    path('edit_note/<int:pk>', edit_note, name='edit_note'),
    path('opennote/<int:pk>/', views.note_individual_web, name='note-detail'),
    path('delete-note/<int:pk>/', views.delete_note, name='delete_note'),
    path('unlock_note/<int:pk>/', views.unlock_note, name='unlock note'),
    path('api/account/<id>', AccountView.as_view()),
    path('api/account/', AccountView.as_view()),
    path('switch_account/<id>', views.switch_account, name = "switch account" ),
    path('add_account/', views.add_account_web, name = "add account"),
    path('edit_account/', views.edit_account_web, name="edit account"),
    path('edit_preferences/', views.edit_account_preferences_web, name = "edit account preferences"),
    path('api/history/<id>', HistoryView.as_view()),
    path('api/history/<id>/filter', HistoryView.as_view()),
    path('filter_history/', views.browsing_history_filter, name = "filter history"),
    path('add_tab/', views.add_tab, name = "add tab"),
    path('open_tab/', views.open_tab, name = "open tab"),
    path('close_tab/<id>', views.close_tab, name = "close tab"),
    path('add_bookmark/<id>/', views.add_bookmark_web, name = "add bookmark"),
    path('delete_bookmark/<id>/', views.delete_bookmark_web, name = "delete bookmark"),
    path('bookmarks/', views.bookmarks_web, name = "bookmarks"),
    path('shared_folders/', views.shared_folders_web, name = "shared folders"),
    path('shared_folder/<int:pk>/', views.shared_folder_individual_web, name = "shared folder"),
    path('add_shared_folder/', views.create_shared_folder_web, name = "add shared folder"),

    path('friends/', views.friends, name = "friends"),
    path('add_friend/', views.add_friend, name = "add friend"),
    path('deny_friend/<int:pk>', views.deny_friend, name = "deny friend"),
    path('accept_friend/<int:pk>', views.accept_friend, name="accept friend"),

flexr/flexr_web/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import *

from django import forms
from django.core.exceptions import ValidationError

class registrationform(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email


choices=(("Business", "Business"),
        ("Personal", "Personal"),
        ("School", "School"),
        ("Private", "Private"),
        ("Kids", "Kids"),
        ("Other", "Other"))

class AccountForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), error_messages={'incomplete': 'Enter a phone number.'},
                validators=[RegexValidator(r'^[0-9]+$', 'Enter a valid phone number.')])
    type_of_account = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), choices = choices)

    class Meta:
        model = Account
        fields = ('username', 'email', 'phone_number', 'type_of_account')


class PreferencesForm(ModelForm):
    class Meta:
        model = Account_Preferences
        # Make homepage a url field? may need to apppend https://www.
        fields = ('home_page', 'sync_enabled', 'searchable_profile', 'cookies_enabled', 'popups_enabled', 'is_dark_mode')

class FilterHistoryForm(forms.Form):
    site = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    start_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False)
    start_time = forms.DateField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}), required=False)
    end_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False)
    end_time = forms.DateField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}), required=False)

    class Meta:
        pass

class EditNoteForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    class Meta:
        model = Note
        # Make homepage a url field? may need to apppend https://www.
        fields = ('title', 'content', 'lock', 'password')

class EditSharedFolder(ModelForm):
    class Meta:
        model = sharedFolder
        fields = ('title', 'description')

class BookmarkFolderForm(ModelForm):
    class Meta:
        model = bookmarkFolder
        fields = ('title', 'bookmarks')

class FilterNoteForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    class Meta:
        pass

class FilterBookmarkForm(forms.Form):
    start_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False)
    start_time = forms.DateField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}), required=False)
    end_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}), required=False)
    end_time = forms.DateField(widget=forms.widgets.TimeInput(attrs={'type': 'time'}), required=False)

    class Meta:
        pass

class BookmarkOnFile(forms.Form):
    class Meta:
        model = bookmarkFolder
        fields = ('bookmarks')

class EditBookmarkForm(ModelForm):
    class Meta:
        model = bookmarkFolder
        # Make homepage a url field? may need to apppend https://www.
        fields = ('title',)

class EditBookmarksFolderForm(ModelForm):
    class Meta:
        model = bookmarkFolder
        # Make homepage a url field? may need to apppend https://www.
        fields = ('bookmarks',)

class CreateNoteForm(ModelForm):

    password = forms.CharField( widget=forms.PasswordInput, required=False)

    class Meta:
        model = Note
        fields = ('title', 'content', 'lock','password')

    def clean_password(self):
        lock = self.cleaned_data.get('lock', False)
        password = self.cleaned_data.get('password', None)
        print(password)
        print(EMPTY_VALUES)
        if lock and password in EMPTY_VALUES:
            raise ValidationError("ENTER PASSWORD")
          
        return password

flexr/templates/flexr_web/bookmark_folder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flexr | Bookmark Folder</title>
    {% load static %}
    <style>
        #plus-icon:hover{
            cursor: pointer;
        }

    </style>
</head>
<body>
    {% include "flexr_web/navbar.html" %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <div class="body">
        <div class="main">
                <div class="suggested sidenav">
                    <a class="navbar-brand" href="/"><img src="{% static 'flexr_logo_2.png' %}" width="100%"></a>
                    <h3>Filter Bookmarks</h3>
                    <div class="filter">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <p style="display: inline;" >
                            {{ field.label_tag }}
                            {{ field }} 
                        </p><br>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </form>
                </div>
                </div>
            <div id = "head" style="text-align: center;">
                <h1 id = "title" style="display: inline;">{{bookmark_folder.title}} Bookmark Folder</h1> 
                <img id="plus-icon" data-toggle="modal" data-target="#edit_folder" src="{% static 'icons/edit.png' %}" width="30px">
                <br>
                <h3 id = "title">{{bookmark_folder.created_date}}</h3> 
            </div>

                <div class="entire_folder col-md-12">
                    <div class = "card-header sticky-top">
                        <h2 style="display: inline;">Bookmarks</h2> 
                        <img id="plus-icon" class="plus-icon" width = 20px; data-toggle="modal" data-target="#add_bm" src="{% static 'icons/plus.png' %}">
                    </div>
                    <div class = "card-body row justify-content-center" >
                        {%for bm in Bookmarks%}
                            
                            <div id = "bookmark" class = "tab card col-lg-5" >
                                <form  method="post" action = "/remove_from_folder/{{bookmark.id}}/{{bookmark_folder.pk}}/">
                                    {% csrf_token %}
                                    <span style="display: inline; position: absolute; left: 0; top: 0; margin-left: 5%; margin-top: 2%;">
                                        <img class="bm" onclick="window.location.href = '/remove_from_folder/{{bm.id}}/{{bookmark_folder.pk}}/'" src="{% static 'icons/cancel.png' %}" width= 15px>
                                    </span>
                                    <input hidden name = "bm_id" value = "{{bm.id}}"></input>
                                    <span style="display: inline;">
                                        <p onclick="window.open('{{bm.site.url}}')"  style="display: inline;">
                                            {%if bm.site.favicon_img_url != None%}
                                                <img class = "icon" src="{{ bm.site.favicon_img_url }}" width="15px">
                                            {%endif%}{{bm.site}}</p>
                                    </span>
                                </form>
                            </div>

                        {%endfor%}
                    </div>
                </div>
            </div>

            <div class="modal fade" id="edit_folder" tabindex="-1" role="dialog" aria-labelledby="edit_folderLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="edit_folderLabel">Edit your folder</h5>
                        <img data-dismiss="modal" src = "{% static 'icons/cancel.png' %}" width=20px>
                        </button>
                    </div>
                    <div class="modal-body">
                            <form method = "POST" action="{% url 'edit_bookmark_folder' bookmark_folder.pk%}">
                                    {% csrf_token %}
                                    {% for field in formb %}
                                    <p>
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </p>
                                    {% endfor %}
                                    <div class="modal-footer">
                                
                                <button type="submit" class="btn btn-primary">Confirm edit</button>
                            </div>
                            </form>
                    </div>
                    </div>
                </div>
            </div>
        <div class="modal fade" id="add_bm" tabindex="-1" role="dialog" aria-labelledby="add_bmLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id = "edit_collabs_modal">
        <div class="modal-header">
            <h5 class="modal-title" id="add_bmLabel">Add bookmarks!</h5>
            <img type="button" class = "icon" data-dismiss="modal" src = "{% static 'icons/cancel.png' %}" width=20px>
            </button>
        </div>
        <div class="modal-body">
                <div class = "add_friend">
                    <div class = "row justify-content-center">
                        <div class="col-md-12">
                            {% for bm in myBookmarks%}
                            <form  method="post" action = "/bookmark_folder/{{bookmark_folder.id}}/add_bookmark/" id = "add_bm_form{{bm.id}}">
                                {% csrf_token %}
                                    <input hidden name = "bm_id" value = "{{bm.id}}"></input>
                                    <p style="display: inline;">{{bm}}{{bm.id}}</p>
                                    <img  class = "icon" src="{% static 'icons/plus.png'%}"  width = 20px style="display: inline;" id = "add-user" onclick="document.getElementById('add_bm_form{{bm.id}}').submit()">
                                    </script>
                                </form>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
</body>
</html>

flexr/templates/flexr_web/bookmarks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flexr | Bookmarks</title>
    {% load static %}
    <style>
        #plus-icon:hover{
            cursor: pointer;
        }
        .folder:hover{
            cursor: pointer;
        }
    </style>
</head>
<body>
    {% include "flexr_web/navbar.html" %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <div class="row body">
        <div class = "main_bm row">
            <div class="suggested sidenav">
                <a class="navbar-brand" href="/"><img src="{% static 'flexr_light.png' %}" width="100%"></a>
                <h3>Filter Bookmarks</h3>
                <div class="filter">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p style="display: inline;" >
                        {{ field.label_tag }}
                        {{ field }} 
                    </p><br>

                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Filter</button>
                </form>
            </div>
            </div>
            <div class="bm_folders col-md-3">
                <div class="row">
                        <div class= "">
                            <h3 style="display:inline;" >Folders</h3>
                            <img style="display:inline; width: 20px !important;"  id="plus-icon" data-toggle="modal" data-target="#add_bookmark_folder" class = "icon" src="{% static 'icons/add_folder.png' %}">
                        </div>
                        
                        <div class="card-body justify-content-center">
                            {%for folder in Folders%}
                                <div id = "bmf" class = "folder card col-md-12" style="height: auto;" >
                                    <img class="close icon" onclick=" var conf = confirm('Do you want to delete this bookmark folder?'); if(conf){ window.location.href = '/delete_bookmark_folder/{{folder.id}}/'}" src="{% static 'icons/cancel.png' %}" width= 15px>
                                    <h4 style="cursor: pointer;" onclick="window.location.href = '/bookmark_folder/{{folder.id}}'" style="display: inline;">{{folder.title}}</h4>
                                    <p>{{folder.bookmarks.all|length}} bookmarks</p>
                                    <!-- <p><a href="{% url 'delete-bookmark-folder' folder.pk%}">Delete Folder</a></p> -->
                                    <br>
                                </div>
                            {%endfor%}
                        </div>

                </div>
            </div>
            <div class="bms col-md-8">
                        <div class="">
                            <h3>All Bookmarks</h3>
                        </div>
                        <div class="card-body justify-content-center row">
                            {%for bm in Bookmarks%}
                                <div id = "bookmark" class = "card col-md-5" style="height: auto;" >
                                    <span style="display: inline;">
                                    <p onclick="window.open('{{bm.site.url}}')"  style="display: inline;">
                                        {%if bm.site.favicon_img_url != None%}
                                            <img class = "icon" src="{{ bm.site.favicon_img_url }}" width="15px">
                                        {%endif%}{{bm.site}}</p>
                                        <img class="bm_icon icon" onclick="window.location.href = '/delete_bookmark/{{bm.site.bookmarked}}'" src="{% static 'icons/bookmarked.png' %}" width= 15px>
                                    </span>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
            </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="add_bookmark_folder" tabindex="-1" role="dialog" aria-labelledby="add_bookmark_folder_Label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="add_bookmark_folder_Label">Add a Bookmark folder</h5>
                <img data-dismiss="modal" class = "icon close" src = "{% static 'icons/cancel.png' %}" width=20px>
                </div>
                <div class="modal-body">
                    <form method = "POST" action="{% url 'create_bookmark_folder' %}">
                            {% csrf_token %}
                            {% for field in formb %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                            {% endfor %}
                            <div class="modal-footer">
                        
                        <button type="submit" class="btn btn-primary">Create Folder</button>
                    </div>
                    </form>
                </div>
            </div>
    </div>
</body>
</html>

flexr/templates/flexr_web/friends.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Friends | Flexr</title>
</head>
<body>
    {% include "flexr_web/navbar.html" %}
    <h1 style="display: inline;">Friends: </h1>
        <div class = "row">
        {% for friend in Friends %}
            <div class = "folder card col-md-3" >
                <h2>{{friend}}</h2>
            </div>
        {% endfor %}
        </div>

</body>
</html>

flexr/templates/flexr_web/notes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flexr | Notes</title>
    {% load static %}
    <style>
        #plus-icon:hover{
            cursor: pointer;
        }
    </style>
</head>
<body>
    {% include "flexr_web/navbar.html" %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    <div class = "body">
        <div class = "main">
                <div class="card-header">
                    <span>
                        <h3 style="display:inline;">Notes</h3><img style="display:inline;" id="plus-icon" width = 20px data-toggle="modal" data-target="#add_note" src="{% static 'icons/plus.png' %}" class = "icon">
                        {%if Notes|length > 0 or searched == True %}
                            {% if Notes|length == 0 and searched == True%}
                                <h1>No notes found.</h1>
                            {%endif%}
                                <form method="POST" action="/notes/" style="display: inline; margin-left: 10%;">
                                    {% csrf_token %}
                                    <span style="display: inline;">
                                        <p style="display: inline;">
                                            <input style = "width: 50%; display: inline;" type="text" name="search" class="form-control" id="id_search">
                                            <button style = "display:inline;" type="submit" class="btn btn-primary">Search</button>
                                        </p>                          
                                    </span>
                                </form>
                        {%else%}
                            <h1>No notes found.</h1>
                        {%endif%}
                    </span>
                </div>

            <div class = "card-body justify-content-center row">
                
                {%for note in Notes%}

                <div id = "note" class = "note card col-lg-3"  style="height: auto !important;">
                    <div class="card-body" style="">
                        <span style="position: absolute; top:0; left:0; margin-left: 5%;">
                            {%if not note.lock%}
                                <img style= "display: inline;"  class="close icon" onclick=" var conf = confirm('Do you want to delete this note?'); if(conf){ window.location.href = '/delete-note/{{note.id}}'}" src="{% static 'icons/cancel.png' %}" width= 15px>
                            {%else%}
                                <img style= "display: inline;"  class="close icon" onclick=" var conf = confirm('You must unlock this note to delete it.'); if(conf){ window.location.href = '/opennote/{{note.id}}'}" src="{% static 'icons/cancel.png' %}" width= 15px>
                            {%endif%}
                        </span>
                    
                        <p style="display: inline;" onclick="window.location.href = '/opennote/{{note.id}}'">{{note}}</p>
                        {%if note.lock%}
                            <img style= "display: inline;" class="lock icon" src="{% static 'icons/lock.png' %}" width= 15px>
                        {%endif%}

                    </div>

                </div>
                {%endfor%}
            </div>

           
        </div>
    </div>
</body>
</html>